# Project: FirstCProgram
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = HelloC.o Variables.o
LINKOBJ  = HelloC.o Variables.o
LIBS     = -L"E:/programs/Dev-Cpp/MinGW64/lib" -L"E:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/programs/Dev-Cpp/MinGW64/include" -I"E:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/programs/Dev-Cpp/MinGW64/include" -I"E:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = FirstCProgram.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

HelloC.o: HelloC.c
	$(CC) -c HelloC.c -o HelloC.o $(CFLAGS)

Variables.o: Variables.c
	$(CC) -c Variables.c -o Variables.o $(CFLAGS)
